name: CI Pipeline

on:
  push:
    branches:
      - main
      - task-*
  pull_request:
    branches:
      - main
      - task-*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10.11', '3.13.3']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pytest pylint black

      - name: Run linting with pylint
        run: |
          pylint src/*.py notebooks/*.ipynb

      - name: Run tests with pytest
        run: |
          pytest

      - name: Run code formatting check with black
        run: |
          black --check .